import React from "react";
import NftPreview from "../media/NftPreview.png";
import "react-pro-sidebar/dist/css/styles.css";
import iconTwitter from "../media/twitter_icon.svg";
import backgrounds from "../media/backgrounds.svg";
import bamboo from "../media/bamboo.svg"; 
import coin from "../media/coin.svg";
import section from "../media/section.svg";
import line from "../media/line.svg";
import iconInsta from "../media/insta_icon.svg";
import chain from "../media/chain.svg";
import rare from "../media/rare.svg";
import gear from "../media/gear.svg";
import rarre from "../media/rarre.svg";
import avatarAxe from "../media/axxe_avatar.png";
import visualnovel from "../media/visualnovel.svg";
import avatarTori from "../media/tori_avatar.png";
import discover from "../media/discover.svg";
import { NavLink } from "react-router-dom";
import avatarMetal from "../media/metal_avatar.png";
import styled from "styled-components";
import { DISCORDLINK, MEDIUMLINK, OPENSEALINK, TWITTERLINK } from "../constants";
import features from "../media/feature_light.png";
import OpenSea from "../media/opensea_overview.svg"
//import MintTitle from "../components/MintTitle";
import bloodmoon from "../media/bloodmoon.svg";
import texture1 from "../media/texture1.png";
import cards from "../media/cards.svg";
import toriiuniverse from "../media/torii-universe.svg";
import ChainLink from "../media/onii_chainlink.svg";
import featurebg from "../media/feature_bg.png";



const Overview = () => {

  return (
    <>

      <div className="overview">
        <section className="overview-hero">
      
          <div className="overview-presentation">
          <img className="chainlink" src={ChainLink} alt="" />
            <div>
            <h1 className="overview-title">Experience a unique 100% decentralized NFT Technology</h1>
            <p>Entirely built On-Chain, with ChainlinkVRF.</p>
            <p>Become a pioneer of NextGen NFTs.</p>
            </div>
            <img className="overview-img" src={NftPreview} alt="" />
            <div className="overview-buttons">
               <NavLink exact to="Mint">
              <HoverButton className="main-button">Mint my first Onii</HoverButton>
              </NavLink>
              <HoverLink href={OPENSEALINK} className="main-button discord" target="_blank">
              <img height="24px" src={OpenSea} />Legacy Collection
             </HoverLink>
            </div>
          
          </div>
          {/* <h1 className="teaser">Collection of 14.000 onii's living on Fantom, coming this October.</h1> */}
      
          <img  className="discover" style={{bottom:'3%'}}src={discover} alt="discover" />
        </section>
        {/* <video width="auto" height="auto" autoPlay loop >
          <source src={oniiTrailer} type="video/ogg"/>
          </video> */}
        <section className="features">
     
        
          {/* <img className="sections" src={section} alt="" /> */}
        <h1>Bringing valuable innovation to NFTs, with exclusive features.</h1>
        <img className="sections" style={{top:'22%'}} src={featurebg} alt="" />
        <div className="feature-list">
            <div className="feature"> 
            <img src={chain} alt="" />
            <span>
            Fully On-Chain <p>Every single phases of the mint are happening on-chain, and stored directly on Ethereum,
            no more rugs.</p>
            </span>
        </div>
           
            <div className="feature">
            <img src={rarre} alt="" />
            <span>
            Provably Rare <p>Each items has its probability to appear engraved on Onii's
            smart contracts, in a total transparency, with ChainlinkVRF. </p>
            </span></div>
            {/* <div className="feature">
            <img src={coin} alt="" />
            <span>
             Passive Incomes <p>8% from every
             benefits generated by our Ecosystem, 48% from the 2nd Edition sales. And 0,88% Royalties forever. </p>
            </span></div> */}
            <div className="feature">
             <img src={rare} alt="" />
             <span>
             High Quality SVGs <p>  Onii's are carefuly designed and optimized
            to get the most attractive vectorial visuals out there.</p> </span></div>
            <div className="feature">
              <img src={backgrounds} alt="" />
              <span>
              Background Rarity <p> Every onii's receive a rarity score, indicated
              by its background. <br /> Ranked on a dedicated Leaderboard.</p></span></div>
              <div className="feature">
            <img src={visualnovel} alt="" />
            <span>
             On-Chain Games <p> Get your onii in unique decentralized game experiences, trading cards, visual novels, like you never seen berfore.
          </p>
            </span></div>
        </div>
        
        </section>
          {/* <section className="vision">
    
          <h1>Invest in the first Multi-Chain NFT Ecosystem of its kind.</h1>
        <div className="onii-intro">
          <div></div>
        <div ><p className="intro">  <strong>Onii'chain</strong> was first made with the ambition to  <strong>push the limits</strong> of NFTs standards,
          with both Technological and Visual potential, to ensure that collectors invest in a <strong>valuable project</strong>, and become<strong> pionneers </strong>of
          <strong> next gen NFTs.</strong>   <br /><br />We managed to introduce a <strong>100% decentralized experience</strong> ,
            and in a total transparency.  With a project <strong>driven by the communty</strong> , we aim to 
            <strong> revolutionize</strong>  the way everyone see NFTs, by continusly offering exclusive and decentralized experiences to users, in addition 
            to <strong>insane rewards </strong>for everyone contributing in the Ecosystem. 
          <br /> 
          With our technology, our main aspiration is also to seek for the <strong>biggest parternships</strong> , mostly outside the "cryptosphere" 
          to contribute in the mass adoption of Blockchain/NFTs technologies.
          <br /> 
          <br /> 
          That's what makes onii'Chain such an<strong> outstanding project</strong>, and the first of its kind.
          </p></div>
        </div>

        </section> */}

      {/* <h1>What's on the Menu...</h1>
  
      <section className="roadmap" >
      <img className="bamboo" src={bamboo} alt="bamboo" />
      <div className="feature-list">
      <div className="feature">
            <img src={bloodmoon} alt="" />
            <span>
            Onii : First Edition (V2)<p> The story will begin with 8753 Onii's.
            Owning a Onii, will be your pass to our growing Ecosystem,
            with exclusives advantages.
            <br />
              <br />
            <a className="" href="">Learn More</a>
            
            </p>
           
            </span></div>
            <img className="discover" src={discover} alt="" />
            <div className="feature roadmap">
            <img src={gear} alt="" />
            <span>
            Onii'Derivative Collections<p> A lot of other collections are planned, so you'll be able to custom
              your Onii, and help him forge it's own personnality. <br />  <br />
            <a className="" href="">Learn More</a>
            </p>
            </span></div>
            <img className="discover" src={discover} alt="" />
            <div className="feature roadmap">
            <img src={toriiuniverse} alt="" />
            <span>
            Exploring the Onii Universe<p> We'll introduce the Onii's background story, and together with the 
            community, we'll build their future in the Torii'Verse (joinning Metaverse).   The ultimate goal is to create the first 100% On-Chain Comic. <br />
            <br /> 
            <a className="" href="">Learn More</a>
            </p>
            </span></div>
            <img className="discover" src={discover} alt="discover" />
            <div className="feature roadmap">
            <img src={cards} alt="" />
            <span>
            Onii'Cards Series <p> Another step in the revolution, you can now collect and trade Onii'Cards without a limit of supply ! 
            Prices drop under 0.01 ETH. <br /> Each Series will
            last only 3 months. With exciting gamified experience ! <br /> <br />
            <a className="" href="">Learn More</a>
            </p>
            </span></div>
            <img className="discover" src={discover} alt="discover" />
            <div className="feature roadmap">
            <img src={visualnovel} alt="" />
            <span>
            Visual Novel Games<p> It's time to play your onii in the Universe we together created. An 
            interactive adventure, crucial choices and different paths are waiting for your onii. After this experience, he'll never be the same...
            
              <br /> <br />
              <a className="" href="">Learn More</a>

            </p>
            </span></div>
            <p style={{textAlign:"center",opacity:"0.8", marginBottom:"3vh"}}> These main features may evolve to match our community wishes. </p> 
          
      </div>
      </section > */}

         <section className="team">
        
          <h1>Onii'Team</h1>
          <p style={{marginBottom:"3vh",opacity:"0.8"}}>Depending on the Community growth and engouement, we're
           likely to hire new members in the team. Stay Tunned. </p>
          <div className="team-showcase">
          <div className="member">
              <img className="team-avatar" src={avatarTori} alt={"Tori avatar"} />
              <div className={"description"}>
                <div className={"name"}>Tori - Artist, UI/UX Designer</div>
          
              </div>
              <div className={"social"}>
                <a href={"https://www.instagram.com/tori_flwr/"} target="_blank">
                  <HoverImg  src={iconInsta} alt={"Instagram"} />
                </a>
              </div>
            </div>
            <div className="member">
              <img className="team-avatar" src={avatarAxe} alt={"Axxe avatar"} />
              <div className={"description"}>
                <div className={"name"}>Axxe - Smart Contract Dev</div>
          

            </div>
            <div className={"social"}>
                <a href={"https://twitter.com/axxedev"} target="_blank">
                  <HoverImg src={iconTwitter} alt={""} />
                </a>
              </div>
              </div>
            <div className="member" >
              <img className="team-avatar" src={avatarMetal} alt={"Metal avatar"} />
              <div className={"description"}>
                <div className={"name"}>Metal - Software Dev</div> 
              </div>
              <div className={"social"}>
                <img src={""} alt={""} />
              </div>
            </div>
          </div>
          <a href="https://yokai-chain.vercel.app/Overview" target="_blank">
          <HoverButton className="main-button discord kk">Discover the Yokai'Chain Project</HoverButton>
          </a>
          <p>On Fantom</p>
      </section>     
     
     
      </div>
    </>
  );
};

const textEmphasis = {
    color: "#FB59E1",
};

const styleHover = `
    -webkit-transition-duration: 0.4s;
    :hover {
      transform: scale(0.95);
    }
    :after {
      transition: all 0.3s;
    }
  `;

const HoverButton = styled.button`
    ${styleHover}
  `;

const HoverImg = styled.img`
    ${styleHover}
  `;

const HoverLink = styled.a`
    ${styleHover}
  `;

export default Overview;
